### ISSUE TITLE
Improve VIM

### ISSUE THREAD

**Issue by paulnovello** [deel-ai/oodeel#26]
Improving VIM:

- [ ] Sometimes tests do not pass
- [x] Hard code PCA with matmuls
- [x] Remove kneed ?

**Comment by cofri** [comment]
Just adding pointers:
https://github.com/deel-ai/oodeel/actions/runs/4458560505/jobs/7830447380
https://github.com/deel-ai/oodeel/actions/runs/4545440875/jobs/8012774287

```
kneed/knee_locator.py:311: UserWarning: No knee/elbow found

assert (0 < self.res_dim and self.res_dim < self.feature_dim), f"Found invalid number of residual dimensions ({self.res_dim}) "
E           TypeError: '<' not supported between instances of 'int' and 'NoneType'
```
